### ISSUE TITLE
Question: why is this action needed?

### ISSUE THREAD

**Issue by benkoshy** [74th/workflow-permission-action#1]
Hi there,

My deepest thanks for putting your work on github.

my understanding of github actions is that only those who have access to the repository would be able to run trigger an action governmened by `workflow_dispatch` - is that correct? 

rgds

Ben

**Comment by 74th** [comment]
> my understanding of github actions is that only those who have access to the repository would be able to run trigger an action government by workflow_dispatch - is that correct?

Yes. 
In my workplace, I gave all employees the right to browse the repository.
Therefore, we needed to create permissions to perform certain actions.
